# Jade Night Theme
background            #0D1612
foreground            #E0EADF

selection_foreground  #0D1612
selection_background  #2D6A4F

cursor                #D4AF37
cursor_text_color     #0D1612
cursor_shape          block

url_color             #52B788

# Black
color0  #0D1612
color8  #1B2B24

# Red
color1  #A44A4A
color9  #C36363

# Green
color2  #2D6A4F
color10 #52B788

# Yellow
color3  #D4AF37
color11 #F1C40F

# Blue
color4  #2A9D8F
color12 #48CAE4

# Magenta
color5  #7B2CBF
color13 #9D4EDD

# Cyan
color6  #1B4332
color14 #40916C

# White
color7  #D8E2DC
color15 #F8F9FA
