$bg_primary = rgba(0F0F0Dff)
$bg_secondary = rgba(141A10ff)
$bg_overlay = rgba(262B23ff)

$fg_primary = rgba(ECE8DDff)
$fg_secondary = rgba(DAD3B9ff)
$fg_bright = rgba(ECE8DDff)

$accent_primary = rgba(9B945Eff)
$accent_secondary = rgba(A79D47ff)
$accent_soft = rgba(AEBABDff)

$success_color = rgba(77CB3Fff)
$error_color = rgba(DF4B4Bff)
$warning_color = rgba(DFDC41ff)

$border_active_primary = rgba(A79D47ff)
$border_active_secondary = rgba(9B945Eff)
$border_inactive = rgba(AEBABDff)

$shadow_color = rgba(262B23ff)

# Background settings
$bgimg = themename.jpg

# Border settings
$borrad = 7
$borsize = 2
