$bg_primary = rgba(0A0A0Aff)
$bg_secondary = rgba(111111ff)
$bg_overlay = rgba(151515ff)

$fg_primary = rgba(F2F2F2ff)
$fg_secondary = rgba(D9D9D9ff)
$fg_bright = rgba(FFFFFFFF)

$accent_primary = rgba(FFFFFFFF)
$accent_secondary = rgba(D9D9D9ff)
$accent_soft = rgba(BFBFBFff)

$success_color = rgba(3FA34Dff)
$error_color = rgba(D32F2Fff)
$warning_color = rgba(E6B800ff)

$border_active_primary = rgba(FFFFFFFF)
$border_active_secondary = rgba(D9D9D9ff)
$border_inactive = rgba(2A2A2Aff)

$shadow_color = rgba(000000aa)

# Background image
$bgimg = eink_1.jpg

# Border settings
$borrad = 2
$borsize = 2
