# E-Ink Theme
background              #0A0A0A
foreground              #F2F2F2

selection_foreground    #0A0A0A
selection_background    #F2F2F2

cursor                  #FFFFFF
cursor_text_color       #0A0A0A
cursor_shape            block

url_color               #BBBBBB

# Black
color0  #0A0A0A
color8  #1A1A1A

# Red
color1  #D32F2F
color9  #FF4C4C

# Green
color2  #3FA34D
color10 #5EDC70

# Yellow
color3  #E6B800
color11 #FFD84D

# Blue
color4  #4C6EF5
color12 #7A95FF

# Magenta
color5  #A855F7
color13 #C084FC

# Cyan
color6  #22B8CF
color14 #66E3F5

# White
color7  #D9D9D9
color15 #FFFFFF
