# Themename Theme
background              #0F0F0D
foreground              #DAD3B9

selection_foreground    #0F0F0D
selection_background    #9B945E

cursor                  #9B945E
cursor_text_color       #0F0F0D
cursor_shape            block

url_color               #AEBABD

# Black
color0 #0F0F0D
color8 #141A10

# Red
color1 #9A3131
color9 #DF4B4B

# Green
color2 #5B9A31
color10 #77CB3F

# Yellow
color3 #BAB83B
color11 #DFDC41

# Blue
color4 #31419A
color12 #435ADD

# Magenta
color5 #9A319A
color13 #D246D2

# Cyan
color6 #318A9A
color14 #45C5DC

# White
color7 #DAD3B9
color15 #ECE8DD
