$bg_primary = rgba(181412ff)
$bg_secondary = rgba(1E1613ff)
$bg_overlay = rgba(382C30ff)

$fg_primary = rgba(DDDEE8ff)
$fg_secondary = rgba(DFCECCff)
$fg_bright = rgba(DDDEE8ff)

$accent_primary = rgba(E09066ff)
$accent_secondary = rgba(A57C5Eff)
$accent_soft = rgba(382C30ff)

$success_color = rgba(4FA542ff)
$error_color = rgba(A54242ff)
$warning_color = rgba(D1DA53ff)

$border_active_primary = rgba(E09066ff)
$border_active_secondary = rgba(A57C5Eff)
$border_inactive = rgba(424D54ff)

$shadow_color = rgba(382C30ff)

# Background settings
$bgimg = the_oldest_dream_1.jpg

# Border settings
$borrad = 7
$borsize = 2
