# The Oldest Dream Theme
background              #181412
foreground              #DFCECC

selection_foreground    #F8F8FF
selection_background    #E09066

cursor                  #E09066
cursor_text_color       #F8F8FF
cursor_shape            block

url_color               #A57C5E

# Black
color0 #181412
color8 #1E1613

# Red
color1 #A54242
color9 #D95555

# Green
color2 #4FA542
color10 #6FE05D

# Yellow
color3 #D1DA53
color11 #E5EF5F

# Blue
color4 #4276A5
color12 #519DE1

# Magenta
color5 #A542A5
color13 #CF55CF

# Cyan
color6 #42A5A0
color14 #4CCFC8

# White
color7 #DFCECC
color15 #DDDEE8
